version: '3'
services:
  redis:
    image: redis:3.0.7
    ports:
      - 6379
  memcached:
    image: memcached:1.5.2
    ports:
      - 11211
    command: memcached -m 64m
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ~/localdocker/mariadb:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
        MYSQL_PASSWORD: my-secret-pw
        MYSQL_USER: admin
        MYSQL_DATABASE: ericpoirier
  php5.6:
    build: ./php5.6
    ports:
       - 80
    environment:
      VIRTUAL_HOST: "*.php56.dev.docker"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./webdev-nginx.conf:/etc/nginx/conf.d/webdev-nginx.conf